# Mahjong app (multi-file build)

This folder is generated by splitting the single-file `index.html` into:
- `index.html` (markup + links)
- `styles.css` (all CSS extracted from <style> blocks)
- `app.js` (all JS extracted from <script> blocks)

## Deploy on GitHub Pages
Put these 3 files in the same folder (repo root is easiest).
Also keep your existing assets (e.g. `dragon-bowl.jpg`) in the same folder, or update paths.

## Cache busting
This build adds `?v=2026-02-27.1` to `styles.css` and `app.js` so iPhones fetch updates after deploy.


## PWA / Add to Home Screen
- iPhone: Share → Add to Home Screen
- Android: Chrome menu → Add to Home screen

## Offline
A simple service worker caches core files for offline play.

Current build version: 2026-02-27.1
